#!/bin/bash

set -e errexit
set -o pipefail
set -o nounset

IP_SERVER=$(ip route get 8.8.8.8 | awk '{print $7}')
PORT_SERVER=$(cat /var/snap/microk8s/current/args/kube-apiserver | sed -n 's/.*--secure-port=\([0-9]*\).*/\1/p')

CLUSTER_NAME='microk8s-cluster'
CONTEXT='microk8s-jenkins'

NAMESPACE='jenkins'
NAME_SERVICE_ACCOUNT='jenkins-user'
SECRET_NAME='jenkins-user-secret' 

SCRIPT_PATH=$(realpath $(dirname $0))
FILE_SA='ServiceAccount.yaml'

if [ ! -f "${SCRIPT_PATH}/${FILE_SA}" ]; then
    echo "File ${FILE_SA} does not exist"
    exit 1
fi

kubectl apply -f $FILE_SA

CA=$(kubectl get secret --namespace="$NAMESPACE" "$SECRET_NAME" -o=jsonpath='{.data.ca\.crt}')
TOKEN=$(kubectl get secret --namespace="$NAMESPACE" "$SECRET_NAME" -o=jsonpath='{.data.token}' | base64 --decode)

cat <<EOF > kubeconfig
apiVersion: v1
kind: Config
clusters:
  - name: ${CLUSTER_NAME}
    cluster:
      certificate-authority-data: ${CA}
      server: https://${IP_SERVER}:${PORT_SERVER}
contexts:
  - name: ${CONTEXT}
    context:
      cluster: ${CLUSTER_NAME}
      namespace: ${NAMESPACE}
      user: ${NAME_SERVICE_ACCOUNT}
users:
  - name: ${NAME_SERVICE_ACCOUNT}
    user:
      token: ${TOKEN}
current-context: ${CONTEXT}
EOF