services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    image: jenkins
    ports:
      - 32440:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    environment:
      - TZ=Europe/Kyiv
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1.5G'
        reservations:
          cpus: '0.4'
          memory: '256M'
          
volumes:
  jenkins_home:
    external: true