apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-user
  namespace: jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-user-secret
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io