services:
  portainer:
    image: registry:2.8.3
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '256M'
          
volumes:
  registry_data:
    external: true