apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  namespace: prometheus
  labels:
     app: prometheus
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k8s_pv/prometheus-server"