services:
  pihole:
    image: pihole/pihole:2024.07.0
    container_name: pihole
    environment:
      - TZ=Europe/Kyiv
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PORT}:80/tcp
    volumes:
      - pihole-etc:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '384M'
        reservations:
          cpus: '0.2'
          memory: '256M'

volumes:
  pihole-etc:
    external: true
  pihole-dnsmasq:
    external: true