apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: grafana
  labels:
     app: grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/k8s_pv/grafana"
