services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 32560:8080
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '384M'
        reservations:
          cpus: '0.5'
          memory: '256M'