services:
  dozzle:
    image: amir20/dozzle:pr-3168
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 32560:8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'