services:
  portainer:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
      - USER_NAME=$USER_NAME
      - USER_ID=$USER_ID
      - DOCKER_GID=$DOCKER_GID
    container_name: portainer
    ports:
      - ${PORT}:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '128M'
          
volumes:
  portainer_data:
    external: true