services:
  portainer:
    image: portainer/portainer-ce:2.20.3-alpine
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.2'
          memory: '256M'
          
volumes:
  portainer_data:
    external: true