services:
  mysql:
    image: mysql:8.0.39-bookworm
    container_name: mysql_db
    networks:
    - phpmna-network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'
        reservations:
          cpus: '0.5'
          memory: '512M'

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - ${PORT_PHPMA}:80
    networks:
      - phpmna-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '256M'
        reservations:
          cpus: '0.2'
          memory: '128M'

volumes:
  mysql_data:
    external: true

networks:
  phpmna-network:
    driver: bridge