services:
  app:
    image: jc21/nginx-proxy-manager:github-pr-3929
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 26540:81 # Admin Web Port
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '256M'

volumes:
  npm-data:
    external: true
  npm-letsencrypt:
    external: true