services:
  app:
    image: jc21/nginx-proxy-manager:github-pr-3929
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - ${PORT}:81
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: true
      PUID: 1000
      PGID: 1000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
        reservations:
          cpus: '0.3'
          memory: '256M'

volumes:
  npm-data:
    external: true
  npm-letsencrypt:
    external: true